# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu1804"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  config.vm.network "forwarded_port", guest: 42000, host: 443

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "hyperv" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  
  # Send commands through Shell
  config.vm.provision "shell", inline: <<-SHELL
    # samba setup #
    sudo apt-get install samba -y # Install samba #
    sed -i -e 's/workgroup=/workgroup=WORKGROUP/g' </etc/samba/smb.conf> # Add WORKGROUp as workgroup to samba config #

    # folder and User/Group setup #
    sudo mkdir /data # makes folder called /data #
    sudo mkdir /data/Testfolder # makes subfolder inside /data called Testfolder #
    sudo newgrp informaticians # create new Group called informaticians #
    sudo usermod -aG informaticians vagrant # add user to group informaticians #
    sudo chgrp -R informaticians: /data # make group informaticians as Owner of /data folder #
    sudo chmod -R g+rw /data # and give the group read and write permissions #

    # add new Folder to SMB config #
    echo [DATA] >> /etc/smb.conf
    echo path = /data >> /etc/smb.conf
    echo valid users = @informaticians >> /etc/smb.conf
    echo browsable = yes >> /etc/smb.conf
    echo writable = yes >> /etc/smb.conf
    echo read only = no >> /etc/smb.conf

    # restart samba for everything to take effect#
    sudo systemctl restart smbd

    # add a User to Samba #
    sudo smbpasswd -a vagrant # add user vagrant to smb #
    echo vagrant # write defaut password to console #
    sudo smbpasswd -e vagrant # enable the user vagrant on smb #

    SHELL
  end
  
end
