version: '3.1'

services:
  # Database
  db:
    image: mysql:8.0.24
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: mybase
      MYSQL_USER: raphael
      MYSQL_PASSWORD: Pa$$w0rd
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.1.0-fpm-alpine
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
volumes:
  db_data: